"""Added ON DELETE CASCADE to foreign keys

Revision ID: 009ebf2771d4
Revises: 53f1ccf6f21d
Create Date: 2025-01-18 10:44:14.939699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009ebf2771d4'
down_revision = '53f1ccf6f21d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyer', schema=None) as batch_op:
        batch_op.drop_constraint('buyer_group_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('buyer_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'group', ['group_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('connection', schema=None) as batch_op:
        batch_op.drop_constraint('connection_user_id_1_fkey', type_='foreignkey')
        batch_op.drop_constraint('connection_user_id_2_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id_2'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id_1'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint('group_present_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'present', ['present_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('present', schema=None) as batch_op:
        batch_op.drop_constraint('present_group_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('present_list_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'list', ['list_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'group', ['group_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('present', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('present_list_id_fkey', 'list', ['list_id'], ['id'])
        batch_op.create_foreign_key('present_group_id_fkey', 'group', ['group_id'], ['id'])

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('group_present_id_fkey', 'present', ['present_id'], ['id'])

    with op.batch_alter_table('connection', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('connection_user_id_2_fkey', 'user', ['user_id_2'], ['id'])
        batch_op.create_foreign_key('connection_user_id_1_fkey', 'user', ['user_id_1'], ['id'])

    with op.batch_alter_table('buyer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('buyer_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('buyer_group_id_fkey', 'group', ['group_id'], ['id'])

    # ### end Alembic commands ###
